spring:
  application:
    name: fiss-server-mgt
  profiles:
    active: dev
  datasource:
    primary:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${fiss.datasource.host}:${fiss.datasource.port}/${fiss.datasource.dbname}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ${fiss.datasource.username}
      password: ${fiss.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  file:
    path: /home/fiss/fiss-server-mgt
  level:
    root: info
    com.yinuo.base.aop: debug
    com.yinuo.fiss.mgt: debug
