server:
  port: 8080
  servlet:
    context-path: /demo-server-mgt
spring:
  application:
    name: demo-server-mgt
  profiles:
    active: local
  datasource:
    primary:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${demo.datasource.host}:${demo.datasource.port}/${demo.datasource.dbname}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ${demo.datasource.username}
      password: ${demo.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
logging:
  file:
    path: /home/demo/demo-server-mgt
  level:
    root: info
    com.yinuo.base.aop: debug
    com.yinuo.demo.mgt: debug
mybatis:
  typeAliasesPackage: com.yinuo.demo.res.database.user
  mapperLocations: classpath:mapper/*.xml
